// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymII2tp01jkfSX03SbcPVoQmoAOXcjPQ',
    appId: '1:365100326265:web:48be019cd87d28fa54a3a8',
    messagingSenderId: '365100326265',
    projectId: 'moneth-250c4',
    authDomain: 'moneth-250c4.firebaseapp.com',
    storageBucket: 'moneth-250c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0xgaIp0ZWH-hWfrATgxS93zgHz_wJOI',
    appId: '1:365100326265:android:4dd0cac8f483f95a54a3a8',
    messagingSenderId: '365100326265',
    projectId: 'moneth-250c4',
    storageBucket: 'moneth-250c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FJCY2gnQ3AssyeyS3YU1iDtn4PPQdj4',
    appId: '1:365100326265:ios:52844136378643bb54a3a8',
    messagingSenderId: '365100326265',
    projectId: 'moneth-250c4',
    storageBucket: 'moneth-250c4.appspot.com',
    iosClientId: '365100326265-k818l4r1icjacn7ru6sptko1mm7h3v3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FJCY2gnQ3AssyeyS3YU1iDtn4PPQdj4',
    appId: '1:365100326265:ios:52844136378643bb54a3a8',
    messagingSenderId: '365100326265',
    projectId: 'moneth-250c4',
    storageBucket: 'moneth-250c4.appspot.com',
    iosClientId: '365100326265-k818l4r1icjacn7ru6sptko1mm7h3v3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
